apiVersion: v1
kind: Service
metadata:
  name: k8s-nginx-affinity
  labels:
    run: k8s-nginx-affinity
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: k8s-nginx
  sessionAffinity: ClientIP
