apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      run: redis
  replicas: 3
  template:
    metadata:
      labels:
        run: redis
    spec:
      containers:
      - name: redis
        imagePullPolicy: IfNotPresent
        image: redis:5.0
        ports:
        - containerPort: 6379

